In [30]:
import tensorflow as tf
import numpy as np

In [10]:
tf.__version__

'2.6.2'

In [11]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [12]:
x = tf.Variable(3, name="x")
y = tf.Variable(5, name="y")
z = x ** 2 + 2*x*y + y**2

In [54]:
w_init = np.arange(4, dtype=np.float32).reshape(2, -1)
W = tf.Variable(w_init, name="W")
b = tf.Variable(tf.ones(shape=(2,1)), name="b")

In [55]:
tf.print(W), tf.print(b), tf.print(W+b)

[[0 1]
 [2 3]]
[[1]
 [1]]
[[1 2]
 [3 4]]


(None, None, None)

In [57]:
@tf.function
def model(x):
    return W * x + b

out_a = model([10, 20])
print(out_a)

tf.Tensor(
[[ 1. 21.]
 [21. 61.]], shape=(2, 2), dtype=float32)


In [59]:
NB_CLASSESS = 10
INPUT_SIZE = 28*28
model = tf.keras.Sequential()


In [61]:
model.add(tf.keras.layers.Dense(
    NB_CLASSESS, 
    input_shape=(INPUT_SIZE,), 
    kernel_initializer='zeros', 
    name='dense_layer', 
    activation='softmax')
)
